#!/bin/bash -ux
# "Install" the backup script and config file.
# Joshua Powers <mrpowersj@gmail.com>

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

install update /usr/local/sbin/
install zfs_backup /usr/local/sbin/
install zfs_health /usr/local/sbin/

crontab cron_entries.txt
