#!/bin/bash -ux
# Using apt do a complete, automated update of system
# Joshua Powers <mrpowersj@gmail.com>

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

apt clean
apt update
apt full-upgrade -y
apt autoremove -y
