#!/usr/bin/env bash
# Basic stuff to setup an intial system
# Joshua Powers <mrpowersj@gmail.com>
set -eux

pushd dots 
for dir in */; do
	echo "Setting up $dir"
	stow -v -t "$HOME" "$dir"
done
popd

