#!/bin/bash
# Basic setup of uvt
# Joshua Powers <mrpowersj@gmail.com>
set -ux

ARCH=$(dpkg --print-architecture)

for release in $(distro-info --supported); do
    uvt-simplestreams-libvirt sync release="$release" arch="$ARCH"
done
