#!/usr/bin/env bash
# Basic stuff to setup an intial system
# Joshua Powers <mrpowersj@gmail.com>
set -eux

getent hosts us.archive.ubuntu.com || {
	echo "Network is not active."
	exit 1
}

APT=(
	ansible
	ansible-lint
	apt-rdepends
	asciinema
	bsdtar
	build-essential
	bzr
	curl
	devscripts
	ethtool
	fonts-powerline
	gconf2
	git
	gnupg
        chromium-browser	
	gparted
	htop
	influxdb-client
	intel-microcode
	ipmitool
	jq
	libavcodec-extra
	libde265-0
	meld
	network-manager-openvpn-gnome
	nfs-common
	openvpn
	pastebinit
	patch
	python3-setuptools
	qemu-kvm
	sbuild
	shellcheck
	squid-deb-proxy-client
	stow
	tox
	tree
	ubuntu-dev-tools
	uvtool
	vim
	virt-manager
	zfsutils-linux
)

UNINSTALL=(
	appstream
	libreoffice-calc
	libreoffice-common
	libreoffice-core
	libreoffice-math
	libreoffice-impress
	libreoffice-writer
	rhythmbox
	shotwell
	thunderbird
	totem
)

#####################################################################
# Clean sources.list

RELEASE=$(lsb_release -c -s)

if true ; then
    cat <<- EOF | sudo tee /etc/apt/sources.list
	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE main restricted universe multiverse 
	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE main restricted universe multiverse 

	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-security main restricted universe multiverse 
	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-updates main restricted universe multiverse 
	deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE-backports main restricted universe multiverse 
	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-security main restricted universe multiverse 
	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-updates main restricted universe multiverse 
	deb-src http://us.archive.ubuntu.com/ubuntu/ $RELEASE-backports main restricted universe multiverse 
	EOF
fi

#####################################################################
# Install and remove as necessary
sudo apt-get clean
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y "${APT[@]}"
sudo apt-get purge -y "${UNINSTALL[@]}"

#####################################################################
# Install snaps
sudo snap install aws-cli --classic
sudo snap install git-ubuntu --classic
sudo snap install hugo
sudo snap install image-status
sudo snap install lxd
sudo snap install multipass --classic --beta
sudo snap install spotify
sudo snap install ustriage --classic
sudo snap install vlc
sudo snap install vscode --classic

#####################################################################
# Configure gnome
if [ -e "$HOME"/Templates ]; then
	rmdir "$HOME"/Templates
fi

if [ -e "$HOME"/Public ]; then
	rmdir "$HOME"/Public
fi

if [ -e "$HOME"/examples.desktop ]; then
	rm "$HOME"/examples.desktop
fi

gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-seconds true
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.notifications show-banners false
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'firefox.desktop', 'vscode_vscode.desktop', 'spotify_spotify.desktop', 'org.gnome.gedit.desktop', 'vlc_vlc.desktop', 'org.gnome.Calculator.desktop', 'gnome-control-center.desktop', 'org.gnome.Screenshot.desktop', 'chromium-browser.desktop']"
gsettings set org.gtk.Settings.FileChooser show-hidden true
gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 24
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false
gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Alt>Tab']"

#####################################################################
# Customize Grub
sudo sed -i 's/GRUB_HIDDEN_TIMEOUT=0/GRUB_HIDDEN_TIMEOUT=/' /etc/default/grub
sudo sed -i 's/GRUB_TIMEOUT=10/GRUB_TIMEOUT=3/' /etc/default/grub
sudo sed -i 's/quiet splash//' /etc/default/grub
sudo sed -i '/GRUB_TERMINAL=console/s/^#//' /etc/default/grub
sudo update-grub

#####################################################################
# Terminal

sed -i 's/HISTSIZE=1000/HISTSIZE=100000/' ~/.bashrc
sed -i 's/HISTFILESIZE=2000/HISTFILESIZE=200000/' ~/.bashrc

# Theme
profile_count=$(gsettings get org.gnome.Terminal.ProfilesList list | wc -c)
if [ "$profile_count" -lt 60 ]; then
	THEME=freya
	wget -O "$THEME" https://raw.githubusercontent.com/Mayccoll/Gogh/master/themes/"$THEME".sh
	chmod +x "$THEME"
	./"$THEME"
	rm "$THEME"
fi

# Prompt
if ! grep -q powerline ~/.bashrc; then
	git clone https://github.com/banga/powerline-shell
	pushd powerline-shell
	sudo python3 setup.py install
	popd
	sudo rm -rf powerline-shell

cat <<- 'EOF' >> ~/.bashrc
function _update_ps1() {
	PS1=$(powerline-shell $?)
}

if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
	PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
EOF

fi


git clone https://github.com/powerline/powerline.git
pushd powerline
sudo python3 setup.py install
popd
sudo rm -rf powerline

#####################################################################
# gedit
gsettings set org.gnome.gedit.preferences.editor auto-save false
gsettings set org.gnome.gedit.preferences.editor bracket-matching true
gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
gsettings set org.gnome.gedit.preferences.editor display-right-margin true
gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
gsettings set org.gnome.gedit.preferences.editor insert-spaces true
gsettings set org.gnome.gedit.preferences.editor right-margin-position 72
gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
gsettings set org.gnome.gedit.preferences.editor tabs-size 4
gsettings set org.gnome.gedit.preferences.editor use-default-font false
gsettings set org.gnome.gedit.preferences.ui max-recents 20

#####################################################################
# lxd
ip link show lxdbr0 || sudo lxc network create lxdbr0 ipv6.address=none ipv4.address=192.168.9.1/24 ipv4.nat=true
sudo lxd init --auto --storage-backend zfs
sudo usermod --append --groups lxd powersj

#####################################################################
# fstab
if ! grep -q x1 /etc/fstab; then
	echo '192.168.1.10:/x1 /home/powersj/Backup    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
		sudo tee -a /etc/fstab > /dev/null
fi

if ! grep -q nas /etc/fstab; then
	echo '192.168.1.10:/nas /home/powersj/NAS    nfs   auto,nofail,noatime,nolock,intr,tcp,actimeo=1800  0   0' |
		sudo tee -a /etc/fstab > /dev/null
fi

#####################################################################
# Reminders of things I need to do that cannot be posted publicly
echo "

YOU MUST COMPLETE THE FOLLOWING:

	* gpg keys
	* ssh private keys
	* work vpn settings

"
